package com.github.dshane001.postbuildexecutorplugin.actions

import com.github.dshane001.postbuildexecutorplugin.model.CommandType

class BuildFileAndExecuteFileCommand: GenericBuildAction(CommandType.REBUILD_FILE_AND_EXECUTE_COMMAND)