package com.github.dshane001.postbuildexecutorplugin.actions

import com.github.dshane001.postbuildexecutorplugin.model.CommandType

class BuildModuleAndExecuteModuleCommand: GenericBuildAction(CommandType.REBUILD_MODULE_AND_EXECUTE_COMMAND)