package com.github.dshane001.postbuildexecutorplugin.actions

import com.github.dshane001.postbuildexecutorplugin.model.CommandType

class BuildProjectAndExecuteProjectCommand: GenericBuildAction(CommandType.REBUILD_PROJECT_AND_EXECUTE_COMMAND)