[versions]
# libraries
annotations = "24.1.0"

# plugins
kotlin = "2.0.0"
changelog = "2.2.0"
gradleIntelliJPlugin = "1.17.3"
qodana = "0.1.13"
kover = "0.8.0"
kotest = "5.9.1"
mockk = "1.13.11"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

# Specify additional librairies here
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest"}
mockk = { module = "io.mockk:mockk", version.ref = "mockk"}


[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }

# Specify additional plugins here
